version: '3.4'

services:
  sunny-narrator:
    image: sunny-narrator
    env_file: .env
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
#    ports:
#      - "${HOST_PORT:-8020}:${CONTAINER_PORT:-8020}"
    volumes:
      - ./books:/app/Books
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              device_ids: ['0']
#              capabilities: [gpu]
